### ISSUE TITLE
Gromacs2020.3-RAMD1.1 error: Aborted (core dumped)

### ISSUE THREAD

**Issue by satvikkg** [HITS-MCM/gromacs-ramd#13] opened 2020-11-13 05:19 UTC
I am using Gromacs2020.3-RAMD1.1. MD run failed with following errror: **Aborted (core dumped)** on GPU(RTX 2080).

**Comment by BerndDoser** [comment] 2020-11-13 07:52
Hi @satvikkg, Thanks for the report. Gromacs2020.3-RAMD1.1 was only a release candidate. Please use Gromacs2020.4-RAMD1.1 instead. If it still crashes, please provide detailed information of your computer and the input files, so that we are able to reproduce the issue. If not already done, run 'make test'.

**Comment by BerndDoser** [comment] 2020-11-13 14:44
I have just received a very similar report for RAMD 1.1 complaining an abort. Unfortunately, I use an std::abort as termination when the maximal receptor-ligand distance is reached. This will be changed in the next release (see #12). I would assume in your case, that the abort is intended and caused by RAMD. Using the '-ramd' flag, a xvg-file should be written with the receptor-ligand distances.

**Comment by satvikkg** [comment] 2020-12-05 13:19
[ramd-kbbox-test.zip](https://github.com/HITS-MCM/gromacs-ramd/files/5647106/ramd-kbbox-test.zip)
I tried running it on the latest release of gromacs-ramd. I am using an RTX2080 on ubuntu 20.04. I followed the tutorial @ https://kbbox.h-its.org/toolbox/tutorials/estimation-of-relative-residence-times-of-protein-ligand-complexes-using-random-acceleration-molecular-dynamics-ramd-implementation-in-gromacs/ . As soon as the distance of the ligand from the receptor reaches 5A, gromacs-ramd throws a Core Aborted error and stops the MD run without writing anything in the .output file.

**Comment by BerndDoser** [comment] 2020-12-07 11:38
In my output the line
```
==== RAMD ==== GROMACS will be stopped after 202300 steps.
```
is printed before gromacs is aborted. This line is needed for the further analysis descried in the tutorial. I will try to reproduce your test case. Thanks for sending it.

**Comment by BerndDoser** [comment] 2020-12-07 17:50
Finally, I have found your issue. The mentioned line is only printed in the mpi binary and not in the thread binary. This issue is already be fixed with the latest commit using the stop condition #12 and will be released soon in the next version.

**Closed** 2021-02-19 08:25 UTC
